version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: npm run dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://api:api@db:5432/api?schema=public
      APP_PORT: 3000
      LOGGER: 'false'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '3005:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes: 
  dbdata: