version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: npm run dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://test:test@db:5432/test?schema=public
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '3005:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes: 
  dbdata: