GET http://localhost:3000/api/users?page=2

###

GET http://localhost:3000/api/users/3

###

POST http://localhost:3000/api/users HTTP/1,1
Content-Type: application/json

{
    "email": "asdf@test.asdfv",
    "name": "name",
    "phone": "12345678",
    "role": 3
}

###

POST http://localhost:3000/api/users/auth HTTP/1,1
Content-Type: application/json

{
    "email": "name@test.test8",
    "password": "password",
}

###

PUT http://localhost:3000/api/users/1

Content-Type: application/json

{
    "name": "item name changed",
}

###

DELETE http://localhost:3000/api/users/1