GET http://localhost:3000/api/users?page=2

###

GET http://localhost:3000/api/users/1

###

POST http://localhost:3000/api/users HTTP/1,1
Content-Type: application/json

{
    "email": "name@test.test6",
    "name": "name",
    "password": "password",
    "phone": "12345678",
    "role": 3,
    "validated": "2022-03-03T18:57:53.813Z"
}

###

PUT http://localhost:3000/api/users/1

Content-Type: application/json

{
    "name": "item name changed",
}

###

DELETE http://localhost:3000/api/users/1